# Generated by Django 4.1.3 on 2022-12-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmi',
            name='height',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bmi',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
