# Generated by Django 4.1.3 on 2022-12-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='healthgoal',
            field=models.CharField(default='not chosen', max_length=50),
        ),
    ]
