# Generated by Django 4.1.3 on 2022-12-17 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_patient_age_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
