# Generated by Django 4.1.3 on 2022-12-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_patient_bmi_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='diet',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
