# Generated by Django 4.1.3 on 2022-12-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_diet_patient_diet_answer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='diet_question',
            new_name='drinking_answer',
        ),
        migrations.AddField(
            model_name='patient',
            name='smoking_answer',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='workout_answer',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
