# Generated by Django 4.1.3 on 2022-12-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_diet_question_patient_drinking_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='subgoal',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
