# Generated by Django 4.1.3 on 2022-12-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_patient_question1_patient_question2'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='answer1',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='answer2',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
