# Generated by Django 4.1.3 on 2022-12-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='tests',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
