# Generated by Django 4.1.3 on 2022-12-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_patient_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='specificanswer1',
            field=models.CharField(default='non', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='specificanswer2',
            field=models.CharField(default='non', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='specificquestion1',
            field=models.CharField(default='non', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='specificquestion2',
            field=models.CharField(default='non', max_length=100),
        ),
    ]
