# Generated by Django 4.1.3 on 2022-12-26 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_patient_specificanswer1_patient_specificanswer2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='answer1',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
