# Generated by Django 4.1.3 on 2022-12-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_patient_answer1'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='specificanswer3',
            field=models.CharField(default='non', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='specificanswer4',
            field=models.CharField(default='non', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='specificanswer5',
            field=models.CharField(default='non', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='specificanswer6',
            field=models.CharField(default='non', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='specificanswer7',
            field=models.CharField(default='non', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='specificanswer8',
            field=models.CharField(default='non', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='specificquestion3',
            field=models.CharField(default='non', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='specificquestion4',
            field=models.CharField(default='non', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='specificquestion5',
            field=models.CharField(default='non', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='specificquestion6',
            field=models.CharField(default='non', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='specificquestion7',
            field=models.CharField(default='non', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='specificquestion8',
            field=models.CharField(default='non', max_length=100),
        ),
    ]
