# Generated by Django 4.1.3 on 2022-12-27 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_patient_specificanswer3_patient_specificanswer4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='specificanswer10',
            field=models.CharField(default='non', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='specificanswer9',
            field=models.CharField(default='non', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='specificquestion10',
            field=models.CharField(default='non', max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='specificquestion9',
            field=models.CharField(default='non', max_length=100),
        ),
    ]
