# Generated by Django 4.1.3 on 2022-12-27 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_patient_specificanswer10_patient_specificanswer9_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='specificanswer4',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='specificquestion4',
        ),
    ]
