# Generated by Django 4.1.3 on 2022-12-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_patient_specificanswer4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_code',
            field=models.IntegerField(default=0),
        ),
    ]
