# Generated by Django 4.1.3 on 2023-01-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_test_test_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='answer2',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
