# Generated by Django 4.1.5 on 2023-01-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_patient_specificanswer1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='answer1',
            field=models.CharField(default='none', max_length=250),
        ),
    ]
