# Generated by Django 4.1.5 on 2023-01-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_patient_answer1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='answer1',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='answer2',
            field=models.CharField(default='none', max_length=400),
        ),
    ]
